name: Deploy to Google Cloud Run

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}


#find the service account: gcloud iam service-accounts list
  #if you don't have one: gcloud iam service-accounts create YOUR_SERVICE_ACCOUNT_NAME          
    #if you don't have necessary roles for service accounts: gcloud projects add-iam-policy-binding YOUR_PROJECT_ID --member=serviceAccount:YOUR_SERVICE_ACCOUNT_NAME@YOUR_PROJECT_ID.iam.gserviceaccount.com --role=roles/cloudrun.admin
          #gcloud projects add-iam-policy-binding YOUR_PROJECT_ID --member=serviceAccount:YOUR_SERVICE_ACCOUNT_NAME@YOUR_PROJECT_ID.iam.gserviceaccount.com --role=roles/iam.serviceAccountUser           

#create key for service account: gcloud iam service-accounts keys create key.json --iam-account YOUR_SERVICE_ACCOUNT_EMAIL



      - name: Create Dockerfile #Adjust this if you use different directory names / versions
        run: |
          cat > Dockerfile << 'EOF'
          FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
          WORKDIR /src
          COPY . .
          RUN dotnet restore "server/api/api.csproj"
          RUN dotnet publish "server/api/api.csproj" -c Release -o /app/publish

          FROM mcr.microsoft.com/dotnet/aspnet:8.0
          WORKDIR /app
          COPY --from=build /app/publish .
          ENV ASPNETCORE_URLS=http://0.0.0.0:8080
          EXPOSE 8080
          ENTRYPOINT ["dotnet", "api.dll"]
          EOF

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ secrets.NAME }} # The name of the "service" (see README.md for example)
          region: europe-north1
          source: .
          dockerfile: Dockerfile
          env_vars: |-
            #DB=${{secrets.DB}} #uncomment and make sure to configure repo secret if you have one
            
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
